# Generated by Django 5.2.6 on 2025-11-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='crm',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
